server:
  port: 8080
  mode: debug

log:
  # 支持debug(-1)、info(0)、warn(1)、error(2)、dpanic(3)、panic(4)、fatal(5)
  level: 0
  # 日志输出格式，支持json or console
  format: console

database:
    driver: mysql
    source: root:Hvrg(CPVYUf^V+Qv@tcp(127.0.0.1:3306)/example?charset=utf8mb4&parseTime=True&loc=Local

redis:
    addr: 127.0.0.1:6379
    password: foobared
    read_timeout: 10
    write_timeout: 10
    dial_timeout: 10
    db: 0

blockchain:
    endpoint: http://localhost:32770
    # chain_id: 5858586
    registry_contract_address: 0x303e3253d30044c87032e6bd723f4a4d060477a0

keystore:
    path: ./keystore/UTC--2024-09-20T02-58-36.049005348Z--5ee5de0cddbee39235624ea1a4ade7cda94829c9
    password: password